version: "3.8"
services:
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - "/usr/src/frontend/node_modules"
      - "./react-frontend:/usr/src/frontend"
  
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  celery_worker_basic:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: flask_celery_worker_basic
    command: /start-celeryworker-basic
    volumes:
      - .:/app
    env_file:
      - .env_dev
    environment:
      - FLASK_APP=trendr
    depends_on:
      - rabbitmq
  
  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: flask_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env_dev
    environment:
      - FLASK_APP=trendr
    depends_on:
      - rabbitmq
  

  flower:
    image: mher/flower
    env_file:
      - .env_dev
    environment:
      - FLASK_APP=trendr
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq