version: "3.8"
services:
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - "/usr/src/frontend/node_modules"
      - "./react-frontend:/usr/src/frontend"
