#!/bin/bash

set -o errexit
set -o nounset

set -o allexport
source /app/.env/.env_apis
source /app/.env/.env_dev
source /app/.env/.env_mail_secrets
set +o allexport

celery -A trendr.celery.workers.sentiment.celery worker --hostname=celery-sentiment%h --loglevel=info -Q sentiment