apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: registry.digitalocean.com/trendr/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry.digitalocean.com/trendr/backend
          imagePullPolicy: Always
          env:
            - name: FLASK_APP
              value: "/app/trendr/app.py"
          ports:
            - containerPort: 5000
      restartPolicy: Always