name: Build & Push Docker Images

on:
  push:
    branches: [ S37/S50-digital-ocean ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v1

      - name: Create .env/
        run: mkdir .env

      - name: Create .env_dev
        run: |
          touch .env/.env_dev

      - name: Create .env_apis
        run: |
          touch .env/.env_apis
          echo TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY }} >> .env/.env_apis
          echo TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET }} >> .env/.env_apis
          echo ETHPLORER_KEY=${{ secrets.ETHPLORER_KEY }} >> .env/.env_apis

      - name: Create .env_mail_secrets
        run: |
          touch .env/.env_mail_secrets
          echo MAIL_SERVER=${{ secrets.MAIL_SERVER }} >> .env/.env_mail_secrets
          echo MAIL_PORT=${{ secrets.MAIL_PORT }} >> .env/.env_mail_secrets
          echo MAIL_USE_SSL=${{ secrets.MAIL_USE_SSL }} >> .env/.env_mail_secrets
          echo MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} >> .env/.env_mail_secrets
          echo MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} >> .env/.env_mail_secrets

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_API_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build Frontend Image
        run: docker build -t registry.digitalocean.com/trendr/frontend:latest react-frontend

      - name: Build Backend Image
        run: docker build -t registry.digitalocean.com/trendr/backend:latest compose/local/flask

      - name: Push Frontend Image to Digital Ocean Container Registry
        run: docker push registry.digitalocean.com/trendr/frontend:latest

      - name: Push Backend Image to Digital Ocean Container Registry
        run: docker push registry.digitalocean.com/trendr/backend:latest