name: Lint Project
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run Black
      uses: rickstaa/action-black@v1

    - name: Install Eslint
      run: yarn --cwd react-frontend install

    - name: Run Eslint
      uses: stefanoeb/eslint-action@1.0.2
      with:
        files: react-frontend/src/