name: Lint Project
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run Black
      uses: rickstaa/action-black@v1

    - name: Run Yarn
      run: yarn --cwd react-frontend install

    - name: Install Eslint
      run: yarn global add eslint

    - name: Run Eslint
      run: eslint react-frontend/src/**/*.js --fix