name: Lint Project
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run Black
      uses: rickstaa/action-black@v1

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Eslint
      run: npm install -g eslint

    - name: Run Eslint
      run: eslint react-frontend/src/**/*.js