name: Build & Test
on:
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create .env/
      run: mkdir .env

    - name: Create .env_dev
      run: |
        touch .env/.env_dev

    - name: Create .env_twitter
      run: |
        touch .env/.env_twitter
        echo TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY }} >> .env/.env_twitter
        echo TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET }} >> .env/.env_twitter

    - name: Create .env_mail_secrets
      run: |
        touch .env/.env_mail_secrets
        echo MAIL_SERVER=${{ secrets.MAIL_SERVER }} >> .env/.env_mail_secrets
        echo MAIL_PORT=${{ secrets.MAIL_PORT }} >> .env/.env_mail_secrets
        echo MAIL_USE_SSL=${{ secrets.MAIL_USE_SSL }} >> .env/.env_mail_secrets
        echo MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} >> .env/.env_mail_secrets
        echo MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} >> .env/.env_mail_secrets

    - name: Build Docker
      run: docker-compose up --build -d

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: python trendr/testing/test_runner.py

    - name: Destroy Docker
      run: docker-compose down -v